name: Enviar Estoque POD

on:
  schedule:
    # todo dia às 19:00 UTC = 15:00 America/Asuncion
    - cron: '0 19 * * *'

on:
  workflow_dispatch:   # perm ite “Run workflow” manualmente na UI
  schedule:
    - cron: '0 19 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install deps
        run: pip install odoorpc

      - name: Executar relatório
        env:
          ODOO_USER: ${{ secrets.ODOO_USER }}
          ODOO_PASS: ${{ secrets.ODOO_PASS }}
        run: python imprimir_message_body.py
