name: Enviar Estoque POD

on:
  workflow_dispatch: {}          # permite rodar manualmente se quiser
  schedule:
    - cron: '30 20 * * *'        # todo dia às 20:30 UTC = 17:30 Brasília

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install deps
        run: pip install odoorpc twilio

      - name: Enviar relatório via WhatsApp
        env:
          ODOO_USER:   ${{ secrets.ODOO_USER }}
          ODOO_PASS:   ${{ secrets.ODOO_PASS }}
          TWILIO_SID:  ${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
          TWILIO_FROM: ${{ secrets.TWILIO_FROM }}
          TWILIO_TO:   ${{ secrets.TWILIO_TO }}
        run: python enviar_estoque_whatsapp.py
