name: Enviar Estoque POD

on:
  workflow_dispatch: {}          # permite rodar manualmente
  schedule:
    - cron: '0 19 * * *'         # todo dia às 19:00 UTC (15:00 Assunção)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install deps
        run: pip install odoorpc

      - name: Executar relatório e salvar em arquivo
        env:
          ODOO_USER: ${{ secrets.ODOO_USER }}
          ODOO_PASS: ${{ secrets.ODOO_PASS }}
        run: |
          python imprimir_message_body.py > report.txt
          echo "Arquivo report.txt gerado com $(wc -l report.txt | awk '{print $1}') linhas."

